From drop to fromPairs
ramdacn/ramda pull request #5
Opened 2017-01-17 17:41 UTC by ZhangCongjie

2017-01-18 04:40 UTC, adispring requested changes

2017-01-18 04:40 UTC, adispring commented on dist/ramda.js
> +     * 返回一个新的list，这个list会舍弃所有满足 `predicate` 方法的头部元素。
中英文之间加个空格？

2017-01-18 04:40 UTC, adispring commented on src/eqProps.js
> + * 借助于 `R.equals` 方法判断两个object的指定属性是否相等。当做一个柯里化的 `prediate` 方法是很有用的。
可以用作柯里化的 predicate

2017-01-18 04:40 UTC, adispring commented on dist/ramda.js
> +     * 根据给定参数的类型返回其对应的空值。Ramda定义了Array (`[]`)，Object (`{}`)，String (`''`)，和 Arguments
如果是一段文字的话，不要换行，两端文字之间空一行

2017-01-18 04:40 UTC, adispring commented on dist/ramda.js
> +     * 所有 `non-primitive` 属性都通过引用来复制。
非原始类型属性？

2017-01-18 04:40 UTC, adispring commented on dist/ramda.js
> +     * 从右向左依次对list中的元素执行 `predicate` 方法，直至返回一个假值。`predicate` 方法需要作为第一个参数传入。
可以保留 `falsy` 英文？

2017-01-18 04:40 UTC, adispring commented on dist/ramda.js
> +     * 接收一个 `predicate` 方法和一个 `filterable` 元素作为参数，返回一个新的相同类型的但
filterable：可被过滤的， foldable：可被折叠（归约）的，
这类单词是保留英文呢，还是翻译出来？

2017-01-18 04:40 UTC, adispring commented on dist/ramda.js
> +     * 一组相等元素中的第一个元素会被保留。
一组 -> 一系列？

2017-01-18 04:40 UTC, adispring commented on dist/ramda.js
> +     * 借助于 `R.equals` 方法判断两个object的指定属性是否相等。当做一个柯里化的 `prediate` 方法是很有用的。
可以用作柯里化的 predicate，如果原文中没有 `` 反引号环绕的名词，就不要再加反引号环绕了吧？

2017-01-18 04:40 UTC, adispring commented on dist/ramda.js
> +     * 返回由 `||` 运算符连接的两个函数的包装函数，如果两个函数中任一函数的执行结果为真值，则返回 `true` ，
返回的是计算结果，不是 true 或 false

2017-01-18 04:40 UTC, adispring commented on src/drop.js
> + * 返回给定参数去除前 `n` 个元素后的结果，该参数可以是list，string或者
这个再一块润饰下？

2017-01-18 04:40 UTC, adispring commented on src/dropLastWhile.js
> + * 从右向左依次对list中的元素执行 `predicate` 方法，直至返回一个假值。`predicate` 方法需要作为第一个参数传入。
保留 `falsy` ?

2017-01-18 04:40 UTC, adispring commented on src/empty.js
> + * 的空值。其它类型的参数如果定义了 `<Type>.empty` 和/或者 `<Type>.prototype.empty` 也是被支持的。
需在一起润饰一下

2017-01-18 04:40 UTC, adispring commented on src/evolve.js
> + * 所有 `non-primitive` 属性都通过引用来复制。
`non-primitive`

2017-01-18 04:40 UTC, adispring commented on src/find.js
> + * 返回给定的列表中第一个满足 `predicate` 方法的元素，如果没有任何元素满足条件则返回 `undefined` 。
没有元素满足 or 任何元素都不满足

2017-01-18 04:40 UTC, adispring commented on src/findIndex.js
> + * 返回给定的列表中第一个满足 `predicate` 方法的元素的索引下标，如果没有任何元素满足条件则返回 `-1` 。
同上

2017-01-18 04:40 UTC, adispring commented on src/findLast.js
> + * 返回给定的列表中最后一个满足 `predicate` 方法的元素，如果没有任何元素满足条件则返回 `undefined` 。
同上

2017-01-18 04:40 UTC, adispring commented on src/findLastIndex.js
> + * 返回给定的列表中最后一个满足 `predicate` 方法的元素的索引下标，如果没有任何元素满足条件则返回 `-1` 。
同上

2017-01-18 04:40 UTC, adispring commented on src/flip.js
> + * 接受一个函数，返回一个新的函数，相比于原函数，新函数的前两个参数顺序做了交换。
交换函数前两个参数的位置 ？

2017-01-18 04:40 UTC, adispring commented on src/forEach.js
> + * 同样要注意, 不同于 `Array.prototype.forEach`，Ramda的 `forEach`返回一个新的数组。
同一段中文不要换行，两段文字之间隔一行

2017-01-18 04:40 UTC, adispring commented on src/forEachObjIndexed.js
> + * 遍历给定的 `object`，对 `object` 中的所有 `key` 和 `value` 执行给定的方法 `fn`。
所有 -> 每对

2017-01-18 05:20 UTC, ZhangCongjie commented on dist/ramda.js
> +     * 接收一个 `predicate` 方法和一个 `filterable` 元素作为参数，返回一个新的相同类型的但
感觉可以保留英文，或者中文（英文）这种？

2017-01-18 05:22 UTC, adispring commented on dist/ramda.js
> +     * @param {Number} a
这个地方为什么删了？

2017-01-18 05:25 UTC, adispring commented on dist/ramda.js
> +     * 根据给定参数的类型返回其对应的空值。Ramda定义了Array (`[]`)，Object (`{}`)，String (`''`)，和 Arguments
Ramda 定义各类型的空值如下：Array (`[]`)，Object (`{}`)，String (`''`) ...

2017-01-18 05:27 UTC, adispring commented on dist/ramda.js
> +     * 返回给定的列表中第一个满足 `predicate` 方法的元素，如果没有任何元素满足条件则返回 `undefined` 。
“方法” 二字可以去掉？

2017-01-18 11:18 UTC, adispring requested changes

2017-01-18 11:18 UTC, adispring commented on dist/ramda.js
> +     * 获取给定列表中的所有元素（包含所有子数组）然后生成一个由这些元素组成的一个新的数组，深度优先。
”获取给定列表中的所有元素（包含所有子数组），然后生成一个由这些元素组成的一个新的数组“ 加了一个逗号，”深度遍历“ 前面换成句号？

2017-01-18 11:18 UTC, adispring commented on dist/ramda.js
> -     * `fn` receives three argument: *(value, key, obj)*.
arguments ?

2017-01-18 11:18 UTC, adispring commented on dist/ramda.js
> +     * 返回给定的列表中第一个满足 `predicate` 方法的元素的索引下标，如果任何元素都满足条件则返回 `-1` 。
任何元素都 -> 没有元素？

2017-01-18 11:18 UTC, adispring commented on dist/ramda.js
> +     * 递归地对第二个参数 `object` 的浅复制进行变换来创建一个新的object，变换方式由第一个参数 `transformation` 来定义。
中英文之间都加一下空格吧？

2017-01-18 11:18 UTC, adispring commented on dist/ramda.js
> +     * 返回由 `||` 运算符连接的两个函数的包装函数，如果两个函数中任一函数的执行结果为 `truth-y`，则返回其执行结果。
一段？

2017-01-18 11:18 UTC, adispring commented on src/dropLast.js
> + * 返回给定 list 去除末尾 `n` 个元素后的结果
去除 list 后 `n` 个元素。

2017-01-18 11:18 UTC, adispring commented on src/evolve.js
> + * 递归地对第二个参数 `object` 的浅复制进行变换来创建一个新的object，变换方式由第一个参数 `transformation` 来定义。
一段内不需要换行

2017-01-20 04:11 UTC, adispring commented on src/indexBy.js
> + * 根据给定函数生成的键，将一个包含多个对象的列表转换为一个包含多个以该键对应值为索引对象的新对象。
mark

2017-01-22 04:02 UTC, adispring commented on src/divide.js
> + * @return {Number}
没恢复全？

2017-01-22 06:28 UTC, adispring commented on src/into.js
> + * step 方法被用作规约函数中的迭代函数。result 方法被用来将最终的 accumulator 转换为相应的返回类型（大部分情况都是 R.identity）。
reduce 翻译成什么好呢？
@xuelangcxy @MissSweety @csqian

2017-01-23 11:57 UTC, adispring commented on src/dropLast.js
> + * 返回给定 list 去除末尾 `n` 个元素后的结果。
去除给定 list 末尾 `n` 个元素。

2017-01-23 11:57 UTC, adispring commented on src/either.js
> + * 注意，这个是短路表达式，意味着如果第一个函数返回 `truth-y` 值的话，第二个函数将不会执行。
不用换行？

2017-01-23 13:44 UTC, adispring commented on src/evolve.js
> + * 所有非原始类型属性都通过引用来复制。
一段一行

2017-02-03 02:11 UTC, csqian commented on src/into.js
> + * step 方法被用作规约函数中的迭代函数。result 方法被用来将最终的 accumulator 转换为相应的返回类型（大部分情况都是 R.identity）。
就是reduce？

2022-01-24 11:00 UTC, closed without merging