Zcx
ramdacn/ramda pull request #6
Opened 2017-01-18 05:45 UTC by MissSweety

first pr from pair-project

2017-01-18 11:13 UTC, ZhangCongjie commented on dist/ramda.js
> +     * 接收两个参数，fst 和 snd，返回数组[fst, snd]。
`fst` `snd` `[fst, snd]`，加反引号可以标注显示

2017-01-22 05:27 UTC, adispring commented on src/pickBy.js
> + * 返回对象的部分副本，这个副本只包含 key 值满足给出的预测条件的属性。
copy -> 拷贝、副本、复制？
@MissSweety @xuelangcxy @csqian

2017-01-22 05:35 UTC, adispring commented on src/partial.js
> + * 接收两个参数： 一个函数 f，还有一个 argument列表。返回新函数 g。
argument 翻译为参数吧？中英文之间空格隔开？

2017-01-22 09:01 UTC, ZhangCongjie commented on src/partial.js
> + * 当函数执行时，g 返回的是 f 作用于初始 argument 和后来提供给 g 的参数的结果。
记得加反引号，下同~

2017-01-22 09:06 UTC, MissSweety commented on src/partial.js
> + * 当函数执行时，g 返回的是 f 作用于初始 argument 和后来提供给 g 的参数的结果。
好的

2017-01-22 09:06 UTC, MissSweety commented on src/partial.js
> + * 接收两个参数： 一个函数 f，还有一个 argument列表。返回新函数 g。
好的

2017-01-22 15:24 UTC, adispring requested changes

2017-01-22 15:24 UTC, adispring commented on src/pair.js
> + * 接收两个参数，`fst` 和 `snd`，返回数组[fst, snd]。
原文的反引号不要去掉？反引号包裹内容与中文空格隔开？
@ZhangCongjie @xuelangcxy @csqian

2017-01-22 15:24 UTC, adispring commented on src/partial.js
> + * 接收两个参数： 一个函数 f，还有一个 argument列表。返回新函数 g。
一段文字不用回车换行哈，一段都是一行即可

2017-01-22 15:24 UTC, adispring commented on src/partialRight.js
> + * 需要两个参数：一个函数f，还有一个argument列表，返回新函数g。
Takes 统一翻译成 “接受”
@ZhangCongjie @xuelangcxy @csqian

2017-01-22 15:24 UTC, adispring commented on src/partition.js
> + * 接收一个 predicate 函数，和一个列表或者其他可过滤的对象，返回一对值。
predicate 保留即可？不用加 “函数”、“方法” ？
@ZhangCongjie @xuelangcxy @csqian 

通过 predicate 将 列表或 "filterable" （可过滤的）对象分成两部分，分别为满足 predicate 和不满足 predicate 的元素。元素类型保持不变。

另一种意译

2017-01-22 15:24 UTC, adispring commented on src/pathEq.js
> + * 确定对象的嵌套路径上是否有某个明确的 value 值，结合 R.path 和 R.equals。
判断对象的嵌套路径上是否存在特定值。通过 `R.equals` 函数进行相等性判断。

in `R.equals` terms 可以统一一下，
@ZhangCongjie  @xuelangcxy @csqian

2017-01-22 15:24 UTC, adispring commented on src/pathEq.js
> + * 最常用的场景：过滤一个 list。
常用于列表过滤 ？

2017-01-22 15:24 UTC, adispring commented on src/pathOr.js
> + * 否则返回给出的缺省值
default value ：缺省值 or 默认值，统一一下
@ZhangCongjie @xuelangcxy @csqian

2017-01-22 15:24 UTC, adispring commented on src/pathOr.js
> + * 如果给出的非空的对象在给出的路径上有值，返回这条路径上的值
given 统一为 “给定”？
@ZhangCongjie @xuelangcxy @csqian 

如果给定非空对象的给定路径上存在值，则将该值返回；否则返回给定的默认值

2017-01-22 15:24 UTC, adispring commented on src/pathSatisfies.js
> + * 如果指定的对象属性在给定的路径下满足给出的 predicate 条件，
给出 -> 给定 ？
如果给定路径下的对象的属性满足 predicate，则返回 `true`；否则返回 `false`

“否则” 前面都用 分号 “；" 隔开
@ZhangCongjie @xuelangcxy @csqian

2017-01-22 15:24 UTC, adispring commented on src/pick.js
> + * 返回对象的部分副本，这个副本仅包含指定键对应的属性。
一段文字是一行哈

2017-01-22 15:24 UTC, adispring commented on src/pick.js
> + * 返回对象的部分副本，这个副本仅包含指定键对应的属性。
副本？拷贝？
@ZhangCongjie @xuelangcxy @csqian

2017-01-22 15:24 UTC, adispring commented on src/pick.js
> + * 返回对象的部分副本，这个副本仅包含指定键对应的属性。
根据给定键值，返回对象的部分拷贝。

2017-01-22 15:24 UTC, adispring commented on src/pick.js
> + * 如果键不存在，则忽略这个属性
如果某个键不存在，则忽略该属性。

2017-01-22 15:24 UTC, adispring commented on src/pick.js
> + * 如果键不存在，则忽略这个属性
每段话结尾要有句号哈

2017-01-22 15:24 UTC, adispring commented on src/pickBy.js
> + * 返回对象的部分副本，这个副本只包含 key 值满足给出的预测条件的属性。
返回对象的部分拷贝，其中仅包含键值满足给定 predicate 的属性。

2017-01-22 15:24 UTC, adispring commented on src/pipeK.js
> + * `R.pipeK(f, g, h)` 相当于 `R.pipe(R.chain(f), R.chain(g), R.chain(h))`。
相当于 ？等价于？

2017-01-22 15:24 UTC, adispring commented on src/pipeP.js
> + * 从左到右执行返回 Promise 的函数的组合。
从左往右？从左到右？
从右往左 or 从右到左？

统一一下
@ZhangCongjie @xuelangcxy @csqian

2017-01-22 15:24 UTC, adispring commented on src/pluck.js
> + * 在给出的列表中的所有对象中，将命名相同的属性抽出来，组成一个新的列表。
将列表中每个对象中特定名称的属性取出，组成一个新的列表。

2017-01-22 15:27 UTC, ZhangCongjie commented on src/partialRight.js
> + * 需要两个参数：一个函数f，还有一个argument列表，返回新函数g。
我翻译成是“接收”

2017-01-22 15:28 UTC, ZhangCongjie commented on src/pathOr.js
> + * 如果给出的非空的对象在给出的路径上有值，返回这条路径上的值
这个我也是给定

2017-01-22 15:28 UTC, ZhangCongjie commented on src/pathOr.js
> + * 否则返回给出的缺省值
我是默认值

2017-01-22 15:28 UTC, ZhangCongjie commented on src/pick.js
> + * 返回对象的部分副本，这个副本仅包含指定键对应的属性。
我翻译的“拷贝”

2017-01-22 15:29 UTC, ZhangCongjie commented on src/pipeP.js
> + * 从左到右执行返回 Promise 的函数的组合。
我的是从左向右...

2017-01-22 15:38 UTC, adispring commented on src/pathOr.js
> + * 否则返回给出的缺省值
默认值+1

2017-01-24 06:26 UTC, MissSweety commented on src/partial.js
> + * 接收两个参数： 一个函数 f，还有一个 argument列表。返回新函数 g。
这个不会很长吗？

2017-01-24 11:01 UTC, adispring commented on src/partial.js
> + * 接收两个参数： 一个函数 `f`，还有一个参数列表，返回新函数 `g`。
部分应用。接收连个参数：函数 `f` 和 参数列表，返回函数  `g`。

2017-01-24 11:01 UTC, adispring commented on src/partial.js
> + * 当函数执行时，`g` 返回的是 `f` 作用于初始参数和后来提供给 `g` 的参数的结果。参数调用顺序是：初始提供的参数，提供给 `g` 的参数。
部分应用。接收连个参数：函数 `f` 和 参数列表，返回函数  `g`。

当调用 `g` 时，将初始参数和 `g` 的参数顺序传给 `f`，并返回 `f` 的执行结果。

这样表述是不是更明确些？
@ZhangCongjie @xuelangcxy @csqian

2017-01-24 11:01 UTC, adispring commented on src/partialRight.js
> + * 接收两个参数：一个函数 `f`，还有一个参数列表，返回新函数 `g`。
同上，
当调用 `g` 时，将 `g` 的参数和初始参数顺序传给 `f`，并返回 `f` 的执行结果。

2017-01-24 11:01 UTC, adispring commented on src/partition.js
> + * 意译：通过 predicate 将列表或 "filterable" （可过滤的）对象分成两部分，分别为满足 predicate 和不满足 predicate 的元素。元素类型保持不变。
选择意译？或者有什么更好的译法？
@ZhangCongjie @csqian @xuelangcxy

2017-01-24 11:01 UTC, adispring commented on src/path.js
> + * 按照给定的路径，取出结果值。
取出给定路径上的值。

2017-01-24 11:01 UTC, adispring commented on src/pickAll.js
> + * 与 `pick` 相似，不过 pickAll 会将不存在的属性以 `key: undefined` 键值对的形式返回。
不过 pickAll 会 -> 但  `pickAll` 会...

2017-01-24 11:01 UTC, adispring commented on src/prop.js
> + * 当作用在一个对象上时，如果指定的属性存在，则返回该属性的值，否则返回 `undefined`。
取出对象中给定 key 对应的 value，如果不存在，则返回 `undefined`。

2017-01-26 04:19 UTC, adispring commented on src/propEq.js
> + * 如果指定的对象属性值用 `R.equals` 判定与给出的值相同，则返回 `true`；否则返回 `false`。
如果指定对象属性与给定的值相等，则返回 `true` ；否则返回 `false` 。通过 ` R.equals` 函数进行相等性判断。

2017-01-26 04:19 UTC, adispring commented on src/propIs.js
> + * 如果指定的对象属性与给定的类型相符，返回 `true` ；否则返回 `false`。
判断指定对象的属性是否为给定的数据类型，是则返回 `true` ；否则返回 `false` 。

2017-01-26 04:19 UTC, adispring commented on src/props.js
> + * 多个 `prop`：输入为键的数组，输出为值的数组。
返回 `prop` 的数组：输入为 keys 数组，输出为对应的 values 数组。values 数组顺序与 keys 的相同。

2017-01-26 04:19 UTC, adispring commented on src/range.js
> + * 返回从 from 到 to 的数字类型列表，包括 `from`，不包括 `to`。
返回从 `from` 到 `to` 之间的所有数的列表。左闭右开（包含 `from`，不包含 `to`）。

2017-01-26 04:19 UTC, adispring commented on src/reduce.js
> + * `R.reduced` 可以用来缩短迭代。
折叠操作。

遍历列表，相继调用二元迭代函数：一个累积值和从数组中取出的当前元素，将结果作为下次迭代的累积值。返回最终累积值。

可以用`R.reduced` 提前终止遍历操作。

`reduce` 的迭代函数接收两个参数 *(acc, value)*，而 `reduceRight` 的迭代函数的参数顺序为 *(value, acc)*

注意：`R.reduce` 与原生 `Array.prototype.reduce` 方法不同，它不会跳过删除或未分配的索引项（稀疏矩阵）。更多关于原生 reduce 的行为，请参考：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce#Description

如果第三个参数自身有 `reduce` 方法，则调用自身的 `reduce` 方法。

2017-01-26 04:19 UTC, adispring commented on src/reduceWhile.js
> + * 与 `reduce`，`reduceWhile` 相似，通过对列表连续的调用迭代函数，最终返回单一的项。`reduceWhile` 支持在每一次迭代前，
与 `reduce` 类似， `reduceWhile` 会遍历列表，相继调用二元迭代函数，并返回最终累积值。 `reduceWhile` 在每次迭代前使用 predicate 进行判断。如果 predicate 返回 `false` ，则提前终止遍历操作，并返回当前累积值。

2017-01-26 04:19 UTC, adispring commented on src/reduced.js
> + * 返回的值应该是一个黑盒子：内部结构不能保证是稳定的。
返回一个封装的值，该值代表 reduce 或 transduce 操作的最终结果。

返回值是一个黑盒子：不能保证内部结构是否稳定。

注意：这个优化不适用于上面未明确列出的函数。例如，现在还不支持 reduceRight。

2017-01-26 04:19 UTC, adispring commented on src/reject.js
> + * 与 `filter` 相反。
`filter` 的补操作。

这个应该怎么翻译？
@ZhangCongjie @xuelangcxy @csqian

2017-01-26 04:19 UTC, adispring commented on src/reject.js
> + * 若在列表位置给出 transformer，则用做 transducer。
用做 -> 用作

2017-01-26 04:19 UTC, adispring commented on src/remove.js
> + * 在 `list` 中移除子列表，这个子列表是从 `start` 开始，包含 `count` 个元素。
移除列表中从 `start` 开始的 `count` 个元素。_ 注意，该操作是非破坏性的：不改变原列表，返回处理后列表的拷贝。

2017-01-26 04:19 UTC, adispring commented on src/repeat.js
> + * 返回长度为 `n` 的包含同一指定值的列表。
生成包含 `n` 个同一元素的数组。

2017-01-26 04:19 UTC, adispring commented on src/replace.js
> + * 用 replacement 替换一个字符串的子字符串或者正则匹配。
用 replacement 替换字符串的子串或正则匹配到的值。

2017-01-26 04:19 UTC, adispring commented on src/reverse.js
> + * 返回元素或者字符顺序与原来相反的新列表或者新字符串。
对列表或字符串的顺序取反。

2017-01-26 04:19 UTC, adispring commented on src/scan.js
> + * Scan 与 reduce 相似，但是返回的是从左开始执行的 reduced 值组成的列表
Scan 与 reduce 类似，但从左侧开始，将每次迭代计算的累积值组成一个列表返回。

2017-01-26 04:19 UTC, adispring commented on src/sequence.js
> + * 将一个[Applicative](https://github.com/fantasyland/fantasy-land#applicative)的
同一段不换行

2017-01-26 04:19 UTC, adispring commented on src/splitWhen.js
> + *  - 两个输出的 list 拼接起来等价于输入的 list。
同一段不换行

2017-01-26 04:19 UTC, adispring commented on src/split.js
> + * 基于给定的分隔符将字符串拆分为字符串数组。
基于 -> 根据

2017-01-26 04:19 UTC, adispring commented on src/splitEvery.js
> + * 将组合拆分成指定长度的 slices。
将集合拆分成指定长度的子集合列表。

2017-01-26 04:19 UTC, adispring commented on src/sortWith.js
> + * 依据 comparator 列表对原列表进行排序。
comparators

2017-01-26 04:19 UTC, adispring commented on src/splitWhen.js
> + *  - 两个输出的 list 拼接起来等价于输入的 list。
遍历列表，根据第一个符合 predicate 的元素的位置，将列表拆分为两部分。第一个符合 predicate 的元素拆分到后一部分中。

2017-01-26 04:19 UTC, adispring commented on src/sort.js
> + * 请注意，返回是一个列表的 **拷贝** ，并没有修改原始列表。
根据 comparator 对列表进行排序。comparator 函数每次接受两个参数，如果第一个值较小，则返回负数；如果第一个值较大，则返回正数；如果两值相等，返回零。注意，返回的是列表的 ** 拷贝 ** ，不会修改原列表。

不换行

2017-01-26 04:19 UTC, adispring commented on src/splitAt.js
> + * 从给定的索引处拆分列表或者字符串
从给定的索引处拆分列表或字符串

2017-01-26 04:19 UTC, adispring commented on src/slice.js
> + * 对于给定的列表或者字符串（或者带有 `slice` 方法的对象），返回从 `fromIndex`（包括）到 `toIndex`（不包括）的元素
或者 -> 或

2017-01-26 04:19 UTC, adispring commented on src/set.js
> + * 给出 lens 和 value ，对给定的数据结构中 lens 聚焦的部分进行设置。
对给定的数据结构，通过 lens 聚焦对其进行设置。

2022-01-24 11:00 UTC, closed without merging